
CREATE TABLE "ADMIN"."PERSON" 
( "PERSONID" NUMBER, 
"PERSONNUMBER" NUMBER, 
"NAME" VARCHAR2(200 BYTE) COLLATE "USING_NLS_COMP", 
"TYPE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP", 
"EFFECTIVEDATE" VARCHAR2(20 BYTE) COLLATE "USING_NLS_COMP"
) DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "ADMIN"."PERSON_PK" ON "ADMIN"."PERSON" ("PERSONID") 
;

ALTER TABLE "ADMIN"."PERSON" ADD CONSTRAINT "PERSON_PK" PRIMARY KEY ("PERSONID")
USING INDEX ENABLE;


